[global]
server_name = "sky0cloud.dpdns.org"
database_backend = "rocksdb"
database_path = "/var/lib/tuwunel"
address = "0.0.0.0"
port = 6167

[federation]
enable = true
trusted_servers = ["sky0cloud.dpdns.org"]

[registration]
enable = true
token = "newpass123"

[email]
enabled = true
smtp_host = "smtp.mailgun.org"
smtp_port = 587
smtp_username = "official@no-reply.skyservers.qzz.io"
smtp_password = "TheBoss123?com"
from_address = "official@no-reply.skyservers.qzz.io"
