server_name = "sky0cloud.dpdns.org"
database_backend = "rocksdb"
database_path = "/var/lib/conduwuit"
address = "0.0.0.0"
port = 6167
allow_federation = true
allow_registration = true
registration_token = "newpass123"
allow_check_for_updates = false
trusted_servers = ["matrix.org"]
max_request_size = 20_000_000
