[global]
server_name = "sky0cloud.dpdns.org"
database_backend = "rocksdb"

# This path must match your docker-compose volume mapping
database_path = "/var/lib/conduwuit"
address = "0.0.0.0"
port = 6167

allow_federation = true
allow_registration = true
registration_token = "newpass123"
trusted_servers = ["matrix.org", "sky0cloud.dpdns.org"]
max_request_size = 20_000_000
allow_check_for_updates = false

[email]
enabled = true
smtp_host = "smtp.mailgun.org"
smtp_port = 587
smtp_username = "official@no-reply.skyservers.qzz.io"
smtp_password = "TheBoss123?com"
from_address = "official@no-reply.skyservers.qzz.io"
